package dev.technologia.guide;
import java.util.*;
import net.minecraft.network.chat.Component;
import net.minecraft.server.network.Filterable;
import net.minecraft.world.item.component.WrittenBookContent;
/** Shared reference atlas and archival metadata. Actual milestones use vanilla advancements. */
public final class FieldGuide {
 private FieldGuide() {}
 public record Chapter(String title,String summary,String icon,int firstPage,int lastPage,boolean planned) {}
 public record Page(String title,List<String> paragraphs,int chapter) {}
 private record Section(String title,String summary,String icon,boolean planned) {}
 // Chapter page ranges are derived from the page list; keep the pages of a chapter together.
 private static final List<Section> SECTIONS=List.of(
  new Section("Workshop","Build the production loop","alloy_smelter",false),
  new Section("Upgrades","Tiers, lanes and blooms","tier_kit_bronze",false),
  new Section("Nexus","Connected storage","storage_terminal",false),
  new Section("Automation","Move power and items","energy_conduit",false),
  new Section("Mining","Selective extraction","digital_miner",false),
  new Section("Controls","Configure your equipment","wrench",false),
  new Section("Diagnostics","Recover a stopped line","basic_circuit",false),
  new Section("Settings","Balance and datapacks","advanced_circuit",false),
  new Section("Alpha status","Capabilities and limits","field_guide",false),
  new Section("Future","The longer journey","chaotic_core",true)
 );
 private static final List<Page> PAGES=List.of(
  new Page("Start a workshop",List.of("Collect copper, iron, tin and redstone. Craft Machine Frames and Basic Circuits, then a Combustion Generator, Ore Crusher and Electric Furnace.","Crush raw metal into two dust, then smelt the dust into ingots. Place machines beside the generator until you can craft Energy Conduits."),0),
  new Page("Coal and biomass",List.of("The combustion generator burns coal or charcoal at 40 FE/t by default. Each fuel lasts 1,600 ticks.","The Biomass Generator makes 20 FE/t by default. Sawdust burns for 200 ticks, saplings for 100, and wheat, kelp or sugar cane for 80. A generator stops burning while its buffer has no room for a full tick of output, so no fuel is wasted."),0),
  new Page("Power in daylight",List.of("Solar Generators make 16 FE/t. Advanced Solar Generators make 64 FE/t. Both need a dimension with skylight, daytime, no rain and open sky above the panel.","Energy Cells store 1,000,000 FE; Advanced Energy Cells store 5,000,000 FE. A first-tier cell sends 200 FE/t across all its connections; tier kits raise capacity and rate."),0),
  new Page("Crushing and smelting",List.of("The crusher doubles raw iron, gold, copper, tin and lead into dust: 100 ticks at 20 FE/t. Coal becomes coal dust in 60 ticks. It also breaks cobblestone into gravel and gravel into sand.","The Electric Furnace uses the loaded vanilla smelting recipes. Its default cycle is 100 ticks at 20 FE/t. It does not award furnace XP yet."),0),
  new Page("Bronze and steel",List.of("Alloy Smelter: 3 copper ingots + 1 tin ingot = 4 bronze ingots. The cycle takes 160 ticks at 30 FE/t.","1 iron ingot + 2 coal dust = 1 steel ingot, taking 240 ticks at 30 FE/t. Either ingredient order works. Both inputs and all output space are checked before processing."),0),
  new Page("Metal plates",List.of("The Metal Press turns one iron, copper, gold, bronze or steel ingot into one matching plate. Each cycle takes 60 ticks at 15 FE/t.","Bronze unlocks the press. Plates are used for solar generation, conduits, tier kits and the building kit. Steel gates the compactor and advanced power."),0),
  new Page("Wood and byproducts",List.of("The Sawmill supports ten vanilla wood families, including stems, stripped logs and wood through their tags. One input yields six planks and one sawdust.","A cycle takes 80 ticks at 15 FE/t. Route sawdust into biomass power, or craft nine sawdust into one charcoal. Full byproduct space stops the machine safely."),0),
  new Page("Compacting bulk materials",List.of("The Compactor packs nine iron, gold or copper ingots into a block. It also packs coal, redstone, lapis, diamonds and emeralds.","Four sand become sandstone; four clay balls become a clay block. These are powered automation recipes, not extra material multiplication."),0),
  new Page("Centrifuge and recycling",List.of("The Centrifuge separates gravel into flint, clay blocks into four clay balls, two moss blocks into bone meal, and four cactus into slime.","The Recycler salvages three matching nuggets from iron or gold tools and armor. It destroys the original item, including enchantments and components. Keep valuable gear away from its input."),0),
  new Page("Sieving for ore",List.of("The Auto Sieve shakes ore fragments out of loose blocks. Gravel gives an iron fragment and sometimes a tin fragment; sand gives copper and sometimes gold; coarse dirt gives lead and sometimes flint. A cycle takes 80 ticks at 15 FE/t.","Four matching fragments crush into one dust. Feed a crusher cobblestone to make gravel, and gravel to make sand, and a sieve line turns plain stone into a slow, renewable trickle of metal."),0),
  new Page("Workshop milestones",List.of("Minecraft Advancements records the workshop milestones, from your first Machine Frame to tier kits and selective mining. Open Progress at the top of this guide to see them as a route: done, next and locked.","The milestones record obtaining the equipment. They do not lock recipes or grant repeatable item rewards. The Field Guide remains a reference atlas."),0),
  new Page("Build a factory",List.of("Use steel or bronze casings, industrial bricks, hazard markings, steel grates, reinforced glass, structural pillars, ventilation grilles, control panels and engineering lamps.","Lamps provide level-15 light. Other building-kit blocks are decorative. Control panels and ventilation grilles face you when placed and turn with the wrench."),0),
  new Page("Machine tiers",List.of("Every powered machine has a tier, from Mk I to Mk VIII. A higher tier works faster, holds more energy, moves more energy per tick and, from Mk III on, spends less energy per operation. Generators and solar panels produce more.","The tier is shown at the top right of the machine screen and on the item. Storage cores and terminals have no tier. Tier statistics come from a data file inside the mod; a datapack cannot change them yet."),1),
  new Page("Installing a tier kit",List.of("Hold a tier kit and use it on a placed machine. Kits install in order: a Mk III kit needs a Mk II machine. The machine keeps its inventory, energy, direction and settings.","Bronze and steel plates make the first kits; resonite, diamonds, netherite scrap, eyes of ender and a nether star make the later ones. Breaking or dismantling a machine keeps its tier on the item."),1),
  new Page("Parallel lanes",List.of("Processors gain lanes with their tier: one at Mk I and Mk II, two at Mk III, then three, four, five, six and eight at Mk VIII. Each lane has its own ingredient slot (two for the Alloy Smelter), its own progress line and works at the same time as the others.","You do not need to sort the input. When a lane is idle and another holds at least two operations' worth of ingredients, the machine moves half of them over. All lanes share the energy buffer and the result slots."),1),
  new Page("Resonance Blooms",List.of("A Resonance Bloom is a resonite-fed plant: craft one from a Resonite Crystal, any small flower and glowstone dust, then plant it on soil. It glows and needs no care.","Each bloom within two blocks of a processing machine, in any direction, raises its speed by 8 percent, up to five blooms and 40 percent. Faster work draws proportionally more power per tick; the energy per operation is unchanged. The machine's energy tooltip shows the current boost."),1),
  new Page("Connect four cores",List.of("A terminal can combine one to four connected Storage Cores: 54 slots per core, up to 216. Connect them with Network Cable or direct contact.","Right-clicking a core opens that individual core. A terminal opens the combined network. Each core keeps its own saved inventory; the catalogue owns no items."),2),
  new Page("Using the catalogue",List.of("Search by item name or registry ID; sort by name or count. Identical components combine into a single entry.","Left-click: withdraw a stack. Right-click: one item. Shift-click: transfer into your inventory. Shift-click inventory items to deposit, or use Deposit held for your cursor stack."),2),
  new Page("Changing a network",List.of("Adding, removing or replacing a core invalidates an open terminal view. Reopen it to get the new capacity safely. A broken cable immediately blocks further transfers.","Networks are limited to four cores and 128 loaded network blocks. A larger network fails closed. No chunks are force-loaded. Autocrafting and storage disks are future systems."),2),
  new Page("Energy conduit routes",List.of("Place Energy Conduits between a generator or cell and consumers. They connect in six directions and keep no energy of their own. A supplier shares one per-tick limit across everything it feeds: 200 FE/t at Mk I, doubling with most tiers.","First priority rotates each tick. Generators may charge cells; cells do not charge each other, preventing buffer ping-pong. Routes inspect at most 128 conduits; a supplier on a longer network shows 'Conduit route too long'."),3),
  new Page("Conduit materials",List.of("The conductor decides how much one supplier can push through a network: copper Energy Conduits carry 200 FE/t, Gold Energy Conduits 1,000 FE/t and Resonite Energy Conduits 5,000 FE/t.","Materials can be mixed, but the weakest conduit on a network sets the limit for the whole network. A block placed directly against a supplier is never limited by conduits."),3),
  new Page("Item Transfer arrows",List.of("Place an Item Transfer between two inventories. It pulls from the rear and sends toward its arrow, up to eight items every eight ticks. Use a wrench to cycle all six directions.","Right-click with an item to set a component-aware ghost filter. Your sample stays in your hand. Empty-hand right-click clears the filter. A redstone signal pauses transfer."),3),
  new Page("An automated alloy line",List.of("Feed copper and tin into the Alloy Smelter with hoppers or Item Transfers. Supply power from a generator through Energy Conduits. Send bronze output to a chest or core.","The smelter only accepts ingredients that form an alloy with what its lane already holds, so two hoppers of copper and tin sort themselves. Results leave from the output slots."),3),
  new Page("Sawmill fuel loop",List.of("A chest of logs feeds a sawmill. A filtered transfer takes sawdust into a Biomass Generator, while another route collects planks. Start the sawmill with an external energy supply.","A sawdust byproduct is a small fuel credit, not a perpetual-motion promise. Energy generation, recipe costs and transfer limits remain explicit."),3),
  new Page("Survey Miner setup",List.of("Place a Survey Miner above the region, give it power, insert an optional filter and press Start. The miner starts paused.","Default radius is four blocks; depth is 32 blocks below the machine. It checks a bounded number of loaded blocks rather than scanning whole chunks at once. Higher tiers scan and mine faster."),4),
  new Page("Ore filters",List.of("The filter slot accepts an ore block or its drop, such as raw iron or coal. Empty means all tagged ores the mining tool can harvest. Only a player sets the filter; hoppers cannot.","The filter is a retained sample. The miner uses iron-pickaxe harvest rules and cannot mine every exotic material. Output-full and no-power states preserve the target."),4),
  new Page("Ownership and rescanning",List.of("The owner must remain online, in the same dimension and able to build. Other players can open a miner but cannot take results or change the filter from its screen; hoppers and breaking the block are not owner-checked. Protected targets use loader break hooks; actual claim-mod behavior still requires pack tests.","When a scan completes the miner pauses. Press Start to scan the area again from the top, or Rescan to restart a scan in progress. Neither regenerates ore."),4),
  new Page("The machine dashboard",List.of("Ingredient slots are amber and sit on the left; result slots are on the right. Only the slots your tier uses are shown. Hover over the energy bar for stored energy, transfer rate and bloom boost.","Each lane shows its own progress line under its ingredients. Pause stops production. Generator and cell buffers may still export stored energy while production is paused."),5),
  new Page("Configuration wrench",List.of("Right-click a machine with the wrench to rotate its front without breaking it or dropping inventory. Item Transfer rotates through all six output directions.","Crouch and use the wrench to dismantle a machine: it goes to your inventory with its tier and stored energy, and its contents drop. Miner ownership still applies."),5),
  new Page("What machines accept",List.of("A machine refuses items it cannot use. A crusher takes only things it can crush, a furnace only what it can smelt, a generator only its fuel. Hoppers and transfers simply keep the item.","If an unusable item is already inside, for example after a datapack changed, the machine moves it to its result slots, where automation can take it away. All faces accept permitted inputs and power; per-face configuration is future work."),5),
  new Page("No power",List.of("Check generator fuel or solar daylight, conduit continuity and consumer energy. A cell cannot charge another cell. Conduit routes never force-load chunks.","A supplier shares its per-tick limit across all consumers, and copper conduits cap a network at 200 FE/t. Use more suppliers, better conduits or tier kits for a large factory."),6),
  new Page("No production",List.of("Check the machine type, recipe ingredients and quantities. Alloys need both ingredients. Output or byproduct space must be available. 'Unsupported item' means an unusable item could not be moved out because the results are full.","Processing resets when the recipe or input identity changes. Adding more of the same input does not erase progress. Datapack reloads can change recipes."),6),
  new Page("Transfer trouble",List.of("Check the Item Transfer arrow and adjacent inventories. Redstone pauses it. The ghost filter matches item components, including custom names.","This version supports vanilla Container and sided-container inventories. Capability-only third-party inventories need a future adapter. Existing recipe viewers also need explicit integration."),6),
  new Page("Balance configuration",List.of("Server settings live in config/technologia.json and require restart. Invalid files are preserved and defaults are used; a missing key keeps its default. /technologia status requires operator permission.","The generator and electric furnace use these settings, and machineSounds turns working sounds off. New processing recipes define their own duration and FE per tick through datapacks."),7),
  new Page("Processing datapacks",List.of("Use type technologia:processing, a machine ID, one or two counted ingredients, a result, optional byproduct with an optional byproduct_chance, time in ticks and energy per tick.","Ingredients accept item or tag matching. See data/technologia/recipe in the jar for working examples. Reload with the normal server datapack workflow."),7),
  new Page("What alpha.4 includes",List.of("Eighteen machine types with eight tiers and parallel lanes, tier kits, wrench dismantling, input refusal, three conduit materials, the Auto Sieve and ore fragments, Resonance Blooms, machine sounds and particles, and a progress page in this guide.","This is still an alpha. Fabric and Forge build coverage does not certify live modpack behavior. Advanced equipment, bosses, fluids, gases and autocrafting remain ahead."),8),
  new Page("Compatibility and saves",List.of("Power adapters use FE on NeoForge/Forge and Team Reborn Energy on Fabric. Conduits can deliver to those energy endpoints. Create kinetic integration is not included. On NeoForge, the Akashic Tome mod should accept this Field Guide like other guide books; this has not been tested in game.","Worlds from alpha.3 load: machine results move to the new result slots and registry IDs are unchanged. Back up worlds before alpha upgrades. Broken machines keep their tier and energy on the item and drop their inventory."),8),
  new Page("Beyond the workshop",List.of("Future branches include configurable ports, fluids and gases, server racks with cooling and autocrafting, data cables, chemistry, reactors, mob farms, nature systems, dimensions, space and the draconic/chaotic endgame.","The long progression is expandable. Color describes function; materials, machinery and capabilities define advancement. Planned systems are not playable content yet."),9)
 );
 public static List<Page> pages(){return PAGES;}
 public static List<Chapter> chapters(){
  List<Chapter> result=new ArrayList<>();
  for(int i=0;i<SECTIONS.size();i++){
   int first=-1,last=-1;
   for(int p=0;p<PAGES.size();p++)if(PAGES.get(p).chapter()==i){if(first<0)first=p;last=p+1;}
   Section s=SECTIONS.get(i);
   result.add(new Chapter(s.title(),s.summary(),s.icon(),Math.max(0,first),Math.max(0,last),s.planned()));
  }
  return List.copyOf(result);
 }
 public static WrittenBookContent content(){
  List<Filterable<Component>> result=new ArrayList<>();
  result.add(Filterable.passThrough(Component.literal("Technologia Workshop Atlas\nUse the native guide to browse chapters.")));
  for(Page page:PAGES) result.add(Filterable.passThrough(Component.literal(page.title()+"\n\n"+String.join("\n\n",page.paragraphs()))));
  return new WrittenBookContent(Filterable.passThrough("Technologia Field Guide"),"Technologia",0,List.copyOf(result),true);
 }
}
