modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"
[[mods]]
modId="technologia"
version="${version}"
displayName="Technologia"
authors="Technologia"
description='''Industrial automation with a unified visual language.'''
[[dependencies.technologia]]
modId="neoforge"
type="required"
versionRange="[21.1.80,)"
ordering="NONE"
side="BOTH"
[[dependencies.technologia]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
