// Derive cached selection/collision boxes from the same geometry as the visual models.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
// 'devices' are blocks with several models (bonsai pot, hand sieve): their shape is the base model, whatever their state.
export function buildFactoryShapes({write,base,machines,decor,devices}) {
 // A Java method may not exceed 64 KB and every box costs about 45 bytes of it, so the table is filled in parts.
 const parts=[[]];let boxesInPart=0;
 for(const name of [...machines,...decor,...devices]){
  const model=JSON.parse(fs.readFileSync(path.join(root,base,`assets/technologia/models/block/${name}.json`),'utf8'));
  const boxes=model.elements.map(e=>[...e.from,...e.to].map(v=>Math.max(0,Math.min(16,v))));
  if(boxesInPart+boxes.length>300){parts.push([]);boxesInPart=0;}
  boxesInPart+=boxes.length;
  parts.at(-1).push(`        shapes.put("${name}", bake(new double[][] {${boxes.map(b=>'{'+b.join(',')+'}').join(',')}}));`);
 }
 write('common/src/main/java/dev/technologia/machine/FactoryShapes.java',`package dev.technologia.machine;

import java.util.*;
import net.minecraft.core.Direction;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.phys.shapes.*;

/** Generated by tools/generate-resources.mjs from the original factory model elements. */
public final class FactoryShapes {
    private static final Map<String, VoxelShape[]> SHAPES = create();
    private static Map<String, VoxelShape[]> create() {
        Map<String, VoxelShape[]> shapes = new HashMap<>();
${parts.map((part,index)=>`        part${index}(shapes);`).join('\n')}
        return Map.copyOf(shapes);
    }
${parts.map((part,index)=>`    private static void part${index}(Map<String, VoxelShape[]> shapes) {\n${part.join('\n')}\n    }`).join('\n')}
    private static VoxelShape[] bake(double[][] boxes) {
        VoxelShape[] result = new VoxelShape[4];
        for (int turn=0; turn<4; turn++) {
            VoxelShape shape = Shapes.empty();
            for (double[] source : boxes) {
                double x1=source[0], z1=source[2], x2=source[3], z2=source[5];
                for (int i=0; i<turn; i++) { double nx1=16-z2, nx2=16-z1; z1=x1; z2=x2; x1=nx1; x2=nx2; }
                shape = Shapes.or(shape, Block.box(x1,source[1],z1,x2,source[4],z2));
            }
            result[turn] = shape.optimize();
        }
        return result;
    }
    public static VoxelShape get(String name, Direction facing) {
        VoxelShape[] shapes = SHAPES.get(name);
        int turn = switch (facing) { case EAST -> 1; case SOUTH -> 2; case WEST -> 3; default -> 0; };
        return shapes == null ? Shapes.block() : shapes[turn];
    }
    private FactoryShapes() {}
}
`);
}
